// 한국 중학교 교과서 카탈로그 — 검정·인정 출판사 시드 포함.
// 사용자가 자기 노트에 입력하는 교과서가 자동으로 라이브러리에 누적됩니다.
// 시드는 textbook-library/data/books.json (Cowork 라이브러리)에서 자동 생성됨.
// 고등 과정은 추후 업데이트 예정.

export const PUBLISHERS = [
  "천재교육",
  "비상교육",
  "미래엔",
  "YBM",
  "동아출판",
  "금성출판사",
  "지학사",
  "좋은책신사고",
  "NE능률",
  "창비교육",
  "교학사",
  "박영사",
] as const;

export type Publisher = (typeof PUBLISHERS)[number];

export const SUBJECTS = ["국어", "영어", "수학", "사회", "역사", "과학"] as const;
export type Subject = (typeof SUBJECTS)[number];

export const GRADES = ["중1", "중2", "중3"] as const;
export type Grade = (typeof GRADES)[number];

export type TextbookEntry = {
  publisher: Publisher;
  grade: Grade;
  subject: Subject;
  title: string;
  author?: string;
};

export const TEXTBOOK_SEED: TextbookEntry[] = [
  { publisher: "미래엔", grade: "중1", subject: "국어", title: "국어", author: "신유식" },
  { publisher: "미래엔", grade: "중1", subject: "국어", title: "국어", author: "민병곤" },
  { publisher: "미래엔", grade: "중1", subject: "수학", title: "수학", author: "황선욱" },
  { publisher: "미래엔", grade: "중1", subject: "사회", title: "사회", author: "손영찬" },
  { publisher: "미래엔", grade: "중2", subject: "역사", title: "역사", author: "이종대" },
  { publisher: "미래엔", grade: "중1", subject: "과학", title: "과학", author: "김태일" },
  { publisher: "미래엔", grade: "중2", subject: "국어", title: "국어", author: "신유식" },
  { publisher: "미래엔", grade: "중2", subject: "과학", title: "과학", author: "김태일" },
  { publisher: "미래엔", grade: "중2", subject: "국어", title: "국어", author: "민병곤" },
  { publisher: "YBM", grade: "중1", subject: "수학", title: "수학", author: "류희찬" },
  { publisher: "YBM", grade: "중1", subject: "과학", title: "과학", author: "권우진" },
  { publisher: "YBM", grade: "중2", subject: "수학", title: "수학", author: "류희찬" },
  { publisher: "YBM", grade: "중2", subject: "과학", title: "과학", author: "권우진" },
  { publisher: "NE능률", grade: "중1", subject: "영어", title: "영어", author: "김기택" },
  { publisher: "NE능률", grade: "중2", subject: "영어", title: "영어", author: "김기택" },
  { publisher: "YBM", grade: "중1", subject: "영어", title: "영어", author: "김은형" },
  { publisher: "YBM", grade: "중2", subject: "영어", title: "영어", author: "김은형" },
  { publisher: "YBM", grade: "중1", subject: "영어", title: "영어", author: "박준언" },
  { publisher: "YBM", grade: "중2", subject: "영어", title: "영어", author: "박준언" },
  { publisher: "동아출판", grade: "중1", subject: "영어", title: "영어", author: "윤정미" },
  { publisher: "동아출판", grade: "중2", subject: "영어", title: "영어", author: "윤정미" },
  { publisher: "동아출판", grade: "중1", subject: "영어", title: "영어", author: "이병민" },
  { publisher: "동아출판", grade: "중2", subject: "영어", title: "영어", author: "이병민" },
  { publisher: "미래엔", grade: "중1", subject: "영어", title: "영어", author: "문영인" },
  { publisher: "미래엔", grade: "중2", subject: "영어", title: "영어", author: "문영인" },
  { publisher: "비상교육", grade: "중1", subject: "영어", title: "영어", author: "황종배" },
  { publisher: "비상교육", grade: "중2", subject: "영어", title: "영어", author: "황종배" },
  { publisher: "지학사", grade: "중1", subject: "영어", title: "영어", author: "송미정" },
  { publisher: "지학사", grade: "중2", subject: "영어", title: "영어", author: "송미정" },
  { publisher: "천재교육", grade: "중1", subject: "영어", title: "영어", author: "소영순" },
  { publisher: "천재교육", grade: "중2", subject: "영어", title: "영어", author: "소영순" },
  { publisher: "천재교육", grade: "중1", subject: "영어", title: "영어", author: "이상기" },
  { publisher: "천재교육", grade: "중2", subject: "영어", title: "영어", author: "이상기" },
  { publisher: "YBM", grade: "중3", subject: "영어", title: "영어", author: "박준언" },
  { publisher: "YBM", grade: "중3", subject: "영어", title: "영어", author: "송미정" },
  { publisher: "동아출판", grade: "중3", subject: "영어", title: "영어", author: "이병민" },
  { publisher: "동아출판", grade: "중3", subject: "영어", title: "영어", author: "윤정미" },
  { publisher: "금성출판사", grade: "중3", subject: "영어", title: "영어", author: "최인철" },
  { publisher: "지학사", grade: "중3", subject: "영어", title: "영어", author: "민찬규" },
  { publisher: "NE능률", grade: "중3", subject: "영어", title: "영어", author: "김성곤" },
  { publisher: "NE능률", grade: "중3", subject: "영어", title: "영어", author: "양현권" },
  { publisher: "천재교육", grade: "중3", subject: "영어", title: "영어", author: "정사열" },
  { publisher: "천재교육", grade: "중3", subject: "영어", title: "영어", author: "이재영" },
  { publisher: "비상교육", grade: "중3", subject: "영어", title: "영어", author: "김진완" },
  { publisher: "미래엔", grade: "중3", subject: "영어", title: "영어", author: "최연희" },
  { publisher: "비상교육", grade: "중2", subject: "수학", title: "수학", author: "이진호" },
  { publisher: "비상교육", grade: "중2", subject: "과학", title: "과학", author: "임태훈" },
  { publisher: "지학사", grade: "중1", subject: "사회", title: "사회", author: "이진석" },
  { publisher: "지학사", grade: "중2", subject: "국어", title: "국어", author: "이삼형" },
  { publisher: "천재교육", grade: "중1", subject: "수학", title: "수학", author: "김동재" },
  { publisher: "비상교육", grade: "중1", subject: "수학", title: "수학", author: "이진호" },
  { publisher: "동아출판", grade: "중1", subject: "수학", title: "수학", author: "박교식" },
  { publisher: "지학사", grade: "중1", subject: "수학", title: "수학", author: "강승필" },
  { publisher: "좋은책신사고", grade: "중1", subject: "수학", title: "수학", author: "강옥기" },
  { publisher: "금성출판사", grade: "중1", subject: "수학", title: "수학", author: "최영기" },
  { publisher: "교학사", grade: "중1", subject: "수학", title: "수학", author: "주미경" },
  { publisher: "미래엔", grade: "중2", subject: "수학", title: "수학", author: "황선욱" },
  { publisher: "천재교육", grade: "중2", subject: "수학", title: "수학", author: "김동재" },
  { publisher: "동아출판", grade: "중2", subject: "수학", title: "수학", author: "박교식" },
  { publisher: "지학사", grade: "중2", subject: "수학", title: "수학", author: "강승필" },
  { publisher: "좋은책신사고", grade: "중2", subject: "수학", title: "수학", author: "강옥기" },
  { publisher: "금성출판사", grade: "중2", subject: "수학", title: "수학", author: "최영기" },
  { publisher: "교학사", grade: "중2", subject: "수학", title: "수학", author: "주미경" },
  { publisher: "미래엔", grade: "중3", subject: "수학", title: "수학", author: "황선욱" },
  { publisher: "천재교육", grade: "중3", subject: "수학", title: "수학", author: "김동재" },
  { publisher: "비상교육", grade: "중3", subject: "수학", title: "수학", author: "이진호" },
  { publisher: "동아출판", grade: "중3", subject: "수학", title: "수학", author: "박교식" },
  { publisher: "지학사", grade: "중3", subject: "수학", title: "수학", author: "강승필" },
  { publisher: "좋은책신사고", grade: "중3", subject: "수학", title: "수학", author: "강옥기" },
  { publisher: "금성출판사", grade: "중3", subject: "수학", title: "수학", author: "최영기" },
  { publisher: "교학사", grade: "중3", subject: "수학", title: "수학", author: "주미경" },
  { publisher: "YBM", grade: "중3", subject: "수학", title: "수학", author: "류희찬" },
  { publisher: "천재교육", grade: "중1", subject: "과학", title: "과학", author: "임성숙" },
  { publisher: "비상교육", grade: "중1", subject: "과학", title: "과학", author: "임태훈" },
  { publisher: "동아출판", grade: "중1", subject: "과학", title: "과학", author: "심규철" },
  { publisher: "지학사", grade: "중1", subject: "과학", title: "과학", author: "오필석" },
  { publisher: "좋은책신사고", grade: "중1", subject: "과학", title: "과학", author: "노태희" },
  { publisher: "금성출판사", grade: "중1", subject: "과학", title: "과학", author: "문성배" },
  { publisher: "천재교육", grade: "중2", subject: "과학", title: "과학", author: "임성숙" },
  { publisher: "동아출판", grade: "중2", subject: "과학", title: "과학", author: "심규철" },
  { publisher: "지학사", grade: "중2", subject: "과학", title: "과학", author: "오필석" },
  { publisher: "좋은책신사고", grade: "중2", subject: "과학", title: "과학", author: "노태희" },
  { publisher: "금성출판사", grade: "중2", subject: "과학", title: "과학", author: "문성배" },
  { publisher: "천재교육", grade: "중1", subject: "사회", title: "사회", author: "허수미" },
  { publisher: "비상교육", grade: "중1", subject: "사회", title: "사회", author: "강창숙" },
  { publisher: "동아출판", grade: "중1", subject: "사회", title: "사회", author: "이우평" },
  { publisher: "금성출판사", grade: "중1", subject: "사회", title: "사회", author: "박형준" },
  { publisher: "박영사", grade: "중1", subject: "사회", title: "사회", author: "서민철" },
  { publisher: "천재교육", grade: "중2", subject: "역사", title: "역사", author: "이종관" },
  { publisher: "비상교육", grade: "중2", subject: "역사", title: "역사", author: "주진오" },
  { publisher: "동아출판", grade: "중2", subject: "역사", title: "역사", author: "왕현종" },
  { publisher: "지학사", grade: "중2", subject: "역사", title: "역사", author: "송호정" },
  { publisher: "금성출판사", grade: "중2", subject: "역사", title: "역사", author: "김덕수" },
  { publisher: "미래엔", grade: "중2", subject: "사회", title: "사회", author: "손영찬" },
  { publisher: "천재교육", grade: "중2", subject: "사회", title: "사회", author: "허수미" },
  { publisher: "비상교육", grade: "중2", subject: "사회", title: "사회", author: "강창숙" },
  { publisher: "동아출판", grade: "중2", subject: "사회", title: "사회", author: "이우평" },
  { publisher: "지학사", grade: "중2", subject: "사회", title: "사회", author: "이진석" },
  { publisher: "금성출판사", grade: "중2", subject: "사회", title: "사회", author: "박형준" },
  { publisher: "박영사", grade: "중2", subject: "사회", title: "사회", author: "서민철" },
  { publisher: "미래엔", grade: "중1", subject: "국어", title: "국어 1-1", author: "신유식" },
  { publisher: "미래엔", grade: "중1", subject: "국어", title: "국어 1-1", author: "민병곤" },
  { publisher: "천재교육", grade: "중1", subject: "국어", title: "국어 1-1", author: "노미숙" },
  { publisher: "천재교육", grade: "중1", subject: "국어", title: "국어 1-1", author: "정호웅" },
  { publisher: "비상교육", grade: "중1", subject: "국어", title: "국어 1-1", author: "박영민" },
  { publisher: "비상교육", grade: "중1", subject: "국어", title: "국어 1-1", author: "박현숙" },
  { publisher: "동아출판", grade: "중1", subject: "국어", title: "국어 1-1", author: "남궁민" },
  { publisher: "지학사", grade: "중1", subject: "국어", title: "국어 1-1", author: "이삼형" },
  { publisher: "창비교육", grade: "중1", subject: "국어", title: "국어 1-1", author: "이도영" },
  { publisher: "좋은책신사고", grade: "중1", subject: "국어", title: "국어 1-1", author: "류수열" },
  { publisher: "미래엔", grade: "중1", subject: "국어", title: "국어 1-2", author: "신유식" },
  { publisher: "미래엔", grade: "중1", subject: "국어", title: "국어 1-2", author: "민병곤" },
  { publisher: "천재교육", grade: "중1", subject: "국어", title: "국어 1-2", author: "노미숙" },
  { publisher: "천재교육", grade: "중1", subject: "국어", title: "국어 1-2", author: "정호웅" },
  { publisher: "비상교육", grade: "중1", subject: "국어", title: "국어 1-2", author: "박영민" },
  { publisher: "비상교육", grade: "중1", subject: "국어", title: "국어 1-2", author: "박현숙" },
  { publisher: "동아출판", grade: "중1", subject: "국어", title: "국어 1-2", author: "남궁민" },
  { publisher: "지학사", grade: "중1", subject: "국어", title: "국어 1-2", author: "이삼형" },
  { publisher: "창비교육", grade: "중1", subject: "국어", title: "국어 1-2", author: "이도영" },
  { publisher: "좋은책신사고", grade: "중1", subject: "국어", title: "국어 1-2", author: "류수열" },
  { publisher: "미래엔", grade: "중1", subject: "수학", title: "수학 1", author: "황선욱" },
  { publisher: "천재교육", grade: "중1", subject: "수학", title: "수학 1", author: "김동재" },
  { publisher: "천재교육", grade: "중1", subject: "수학", title: "수학 1", author: "김화경" },
  { publisher: "비상교육", grade: "중1", subject: "수학", title: "수학 1", author: "이진호" },
  { publisher: "동아출판", grade: "중1", subject: "수학", title: "수학 1", author: "박교식" },
  { publisher: "지학사", grade: "중1", subject: "수학", title: "수학 1", author: "강승필" },
  { publisher: "좋은책신사고", grade: "중1", subject: "수학", title: "수학 1", author: "강옥기" },
  { publisher: "금성출판사", grade: "중1", subject: "수학", title: "수학 1", author: "최영기" },
  { publisher: "교학사", grade: "중1", subject: "수학", title: "수학 1", author: "주미경" },
  { publisher: "YBM", grade: "중1", subject: "수학", title: "수학 1", author: "류희찬" },
  { publisher: "미래엔", grade: "중1", subject: "사회", title: "사회 ①", author: "손영찬" },
  { publisher: "천재교육", grade: "중1", subject: "사회", title: "사회 ①", author: "허수미" },
  { publisher: "비상교육", grade: "중1", subject: "사회", title: "사회 ①", author: "강창숙" },
  { publisher: "동아출판", grade: "중1", subject: "사회", title: "사회 ①", author: "이우평" },
  { publisher: "지학사", grade: "중1", subject: "사회", title: "사회 ①", author: "이진석" },
  { publisher: "금성출판사", grade: "중1", subject: "사회", title: "사회 ①", author: "박형준" },
  { publisher: "박영사", grade: "중1", subject: "사회", title: "사회 ①", author: "서민철" },
  { publisher: "미래엔", grade: "중1", subject: "과학", title: "과학 1", author: "김태일" },
  { publisher: "천재교육", grade: "중1", subject: "과학", title: "과학 1", author: "임성숙" },
  { publisher: "천재교육", grade: "중1", subject: "과학", title: "과학 1", author: "정대홍" },
  { publisher: "비상교육", grade: "중1", subject: "과학", title: "과학 1", author: "임태훈" },
  { publisher: "동아출판", grade: "중1", subject: "과학", title: "과학 1", author: "심규철" },
  { publisher: "지학사", grade: "중1", subject: "과학", title: "과학 1", author: "오필석" },
  { publisher: "좋은책신사고", grade: "중1", subject: "과학", title: "과학 1", author: "노태희" },
  { publisher: "금성출판사", grade: "중1", subject: "과학", title: "과학 1", author: "문성배" },
  { publisher: "YBM", grade: "중1", subject: "과학", title: "과학 1", author: "권우진" },
  { publisher: "미래엔", grade: "중2", subject: "국어", title: "국어 2-1", author: "신유식" },
  { publisher: "미래엔", grade: "중2", subject: "국어", title: "국어 2-1", author: "민병곤" },
  { publisher: "천재교육", grade: "중2", subject: "국어", title: "국어 2-1", author: "노미숙" },
  { publisher: "천재교육", grade: "중2", subject: "국어", title: "국어 2-1", author: "정호웅" },
  { publisher: "비상교육", grade: "중2", subject: "국어", title: "국어 2-1", author: "박영민" },
  { publisher: "비상교육", grade: "중2", subject: "국어", title: "국어 2-1", author: "박현숙" },
  { publisher: "동아출판", grade: "중2", subject: "국어", title: "국어 2-1", author: "남궁민" },
  { publisher: "지학사", grade: "중2", subject: "국어", title: "국어 2-1", author: "이삼형" },
  { publisher: "창비교육", grade: "중2", subject: "국어", title: "국어 2-1", author: "이도영" },
  { publisher: "좋은책신사고", grade: "중2", subject: "국어", title: "국어 2-1", author: "류수열" },
  { publisher: "미래엔", grade: "중2", subject: "국어", title: "국어 2-2", author: "신유식" },
  { publisher: "미래엔", grade: "중2", subject: "국어", title: "국어 2-2", author: "민병곤" },
  { publisher: "천재교육", grade: "중2", subject: "국어", title: "국어 2-2", author: "노미숙" },
  { publisher: "천재교육", grade: "중2", subject: "국어", title: "국어 2-2", author: "정호웅" },
  { publisher: "비상교육", grade: "중2", subject: "국어", title: "국어 2-2", author: "박영민" },
  { publisher: "비상교육", grade: "중2", subject: "국어", title: "국어 2-2", author: "박현숙" },
  { publisher: "동아출판", grade: "중2", subject: "국어", title: "국어 2-2", author: "남궁민" },
  { publisher: "지학사", grade: "중2", subject: "국어", title: "국어 2-2", author: "이삼형" },
  { publisher: "창비교육", grade: "중2", subject: "국어", title: "국어 2-2", author: "이도영" },
  { publisher: "좋은책신사고", grade: "중2", subject: "국어", title: "국어 2-2", author: "류수열" },
  { publisher: "미래엔", grade: "중2", subject: "수학", title: "수학 2", author: "황선욱" },
  { publisher: "천재교육", grade: "중2", subject: "수학", title: "수학 2", author: "김동재" },
  { publisher: "천재교육", grade: "중2", subject: "수학", title: "수학 2", author: "김화경" },
  { publisher: "비상교육", grade: "중2", subject: "수학", title: "수학 2", author: "이진호" },
  { publisher: "동아출판", grade: "중2", subject: "수학", title: "수학 2", author: "박교식" },
  { publisher: "지학사", grade: "중2", subject: "수학", title: "수학 2", author: "강승필" },
  { publisher: "좋은책신사고", grade: "중2", subject: "수학", title: "수학 2", author: "강옥기" },
  { publisher: "금성출판사", grade: "중2", subject: "수학", title: "수학 2", author: "최영기" },
  { publisher: "교학사", grade: "중2", subject: "수학", title: "수학 2", author: "주미경" },
  { publisher: "YBM", grade: "중2", subject: "수학", title: "수학 2", author: "류희찬" },
  { publisher: "미래엔", grade: "중2", subject: "사회", title: "사회 ②", author: "손영찬" },
  { publisher: "천재교육", grade: "중2", subject: "사회", title: "사회 ②", author: "허수미" },
  { publisher: "비상교육", grade: "중2", subject: "사회", title: "사회 ②", author: "강창숙" },
  { publisher: "동아출판", grade: "중2", subject: "사회", title: "사회 ②", author: "이우평" },
  { publisher: "지학사", grade: "중2", subject: "사회", title: "사회 ②", author: "이진석" },
  { publisher: "금성출판사", grade: "중2", subject: "사회", title: "사회 ②", author: "박형준" },
  { publisher: "박영사", grade: "중2", subject: "사회", title: "사회 ②", author: "서민철" },
  { publisher: "미래엔", grade: "중2", subject: "과학", title: "과학 2", author: "김태일" },
  { publisher: "천재교육", grade: "중2", subject: "과학", title: "과학 2", author: "임성숙" },
  { publisher: "천재교육", grade: "중2", subject: "과학", title: "과학 2", author: "정대홍" },
  { publisher: "비상교육", grade: "중2", subject: "과학", title: "과학 2", author: "임태훈" },
  { publisher: "동아출판", grade: "중2", subject: "과학", title: "과학 2", author: "심규철" },
  { publisher: "지학사", grade: "중2", subject: "과학", title: "과학 2", author: "오필석" },
  { publisher: "좋은책신사고", grade: "중2", subject: "과학", title: "과학 2", author: "노태희" },
  { publisher: "금성출판사", grade: "중2", subject: "과학", title: "과학 2", author: "문성배" },
  { publisher: "YBM", grade: "중2", subject: "과학", title: "과학 2", author: "권우진" },
  { publisher: "미래엔", grade: "중2", subject: "역사", title: "역사 ①", author: "이종대" },
  { publisher: "천재교육", grade: "중2", subject: "역사", title: "역사 ①", author: "이종관" },
  { publisher: "비상교육", grade: "중2", subject: "역사", title: "역사 ①", author: "주진오" },
  { publisher: "동아출판", grade: "중2", subject: "역사", title: "역사 ①", author: "왕현종" },
  { publisher: "지학사", grade: "중2", subject: "역사", title: "역사 ①", author: "송호정" },
  { publisher: "금성출판사", grade: "중2", subject: "역사", title: "역사 ①", author: "김덕수" },
  { publisher: "미래엔", grade: "중3", subject: "국어", title: "국어 3-1", author: "신유식" },
  { publisher: "미래엔", grade: "중3", subject: "국어", title: "국어 3-1", author: "민병곤" },
  { publisher: "천재교육", grade: "중3", subject: "국어", title: "국어 3-1", author: "노미숙" },
  { publisher: "천재교육", grade: "중3", subject: "국어", title: "국어 3-1", author: "정호웅" },
  { publisher: "비상교육", grade: "중3", subject: "국어", title: "국어 3-1", author: "박영민" },
  { publisher: "비상교육", grade: "중3", subject: "국어", title: "국어 3-1", author: "박현숙" },
  { publisher: "동아출판", grade: "중3", subject: "국어", title: "국어 3-1", author: "남궁민" },
  { publisher: "지학사", grade: "중3", subject: "국어", title: "국어 3-1", author: "이삼형" },
  { publisher: "창비교육", grade: "중3", subject: "국어", title: "국어 3-1", author: "이도영" },
  { publisher: "좋은책신사고", grade: "중3", subject: "국어", title: "국어 3-1", author: "류수열" },
  { publisher: "미래엔", grade: "중3", subject: "국어", title: "국어 3-2", author: "신유식" },
  { publisher: "미래엔", grade: "중3", subject: "국어", title: "국어 3-2", author: "민병곤" },
  { publisher: "천재교육", grade: "중3", subject: "국어", title: "국어 3-2", author: "노미숙" },
  { publisher: "천재교육", grade: "중3", subject: "국어", title: "국어 3-2", author: "정호웅" },
  { publisher: "비상교육", grade: "중3", subject: "국어", title: "국어 3-2", author: "박영민" },
  { publisher: "비상교육", grade: "중3", subject: "국어", title: "국어 3-2", author: "박현숙" },
  { publisher: "동아출판", grade: "중3", subject: "국어", title: "국어 3-2", author: "남궁민" },
  { publisher: "지학사", grade: "중3", subject: "국어", title: "국어 3-2", author: "이삼형" },
  { publisher: "창비교육", grade: "중3", subject: "국어", title: "국어 3-2", author: "이도영" },
  { publisher: "좋은책신사고", grade: "중3", subject: "국어", title: "국어 3-2", author: "류수열" },
  { publisher: "미래엔", grade: "중3", subject: "수학", title: "수학 3", author: "황선욱" },
  { publisher: "천재교육", grade: "중3", subject: "수학", title: "수학 3", author: "김동재" },
  { publisher: "천재교육", grade: "중3", subject: "수학", title: "수학 3", author: "김화경" },
  { publisher: "비상교육", grade: "중3", subject: "수학", title: "수학 3", author: "이진호" },
  { publisher: "동아출판", grade: "중3", subject: "수학", title: "수학 3", author: "박교식" },
  { publisher: "지학사", grade: "중3", subject: "수학", title: "수학 3", author: "강승필" },
  { publisher: "좋은책신사고", grade: "중3", subject: "수학", title: "수학 3", author: "강옥기" },
  { publisher: "금성출판사", grade: "중3", subject: "수학", title: "수학 3", author: "최영기" },
  { publisher: "교학사", grade: "중3", subject: "수학", title: "수학 3", author: "주미경" },
  { publisher: "YBM", grade: "중3", subject: "수학", title: "수학 3", author: "류희찬" },
  { publisher: "미래엔", grade: "중3", subject: "과학", title: "과학 3", author: "김태일" },
  { publisher: "천재교육", grade: "중3", subject: "과학", title: "과학 3", author: "임성숙" },
  { publisher: "천재교육", grade: "중3", subject: "과학", title: "과학 3", author: "정대홍" },
  { publisher: "비상교육", grade: "중3", subject: "과학", title: "과학 3", author: "임태훈" },
  { publisher: "동아출판", grade: "중3", subject: "과학", title: "과학 3", author: "심규철" },
  { publisher: "지학사", grade: "중3", subject: "과학", title: "과학 3", author: "오필석" },
  { publisher: "좋은책신사고", grade: "중3", subject: "과학", title: "과학 3", author: "노태희" },
  { publisher: "금성출판사", grade: "중3", subject: "과학", title: "과학 3", author: "문성배" },
  { publisher: "YBM", grade: "중3", subject: "과학", title: "과학 3", author: "권우진" },
  { publisher: "미래엔", grade: "중3", subject: "역사", title: "역사 ②", author: "이종대" },
  { publisher: "천재교육", grade: "중3", subject: "역사", title: "역사 ②", author: "이종관" },
  { publisher: "비상교육", grade: "중3", subject: "역사", title: "역사 ②", author: "주진오" },
  { publisher: "동아출판", grade: "중3", subject: "역사", title: "역사 ②", author: "왕현종" },
  { publisher: "지학사", grade: "중3", subject: "역사", title: "역사 ②", author: "송호정" },
  { publisher: "금성출판사", grade: "중3", subject: "역사", title: "역사 ②", author: "김덕수" },
];

export function filterTextbooks(
  custom: TextbookEntry[],
  filter: { publisher?: Publisher; grade?: Grade; subject?: Subject },
): TextbookEntry[] {
  const all = [...TEXTBOOK_SEED, ...custom];
  return all.filter(
    (t) =>
      (!filter.publisher || t.publisher === filter.publisher) &&
      (!filter.grade || t.grade === filter.grade) &&
      (!filter.subject || t.subject === filter.subject),
  );
}
